import asyncio
import json
import time
import hashlib
import uvicorn
from typing import AsyncGenerator
from fastapi import FastAPI, Request, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

app = FastAPI(title="AI Engine with Caching & Rate Limiting", version="1.0.0")

# In-memory stores
CACHE_STORE = {}
RATE_LIMIT_STORE = {}
MAX_REQUESTS_PER_MINUTE = 3  # Set to 3 so you can test rate limiting easily

class ChatRequest(BaseModel):
    prompt: str = Field(..., min_length=1, description="Question for the AI")

# 1. Cache Key Generator (SHA-256 Hash)
def get_cache_key(prompt: str) -> str:
    normalized = prompt.strip().lower()
    return hashlib.sha256(normalized.encode()).hexdigest()

# 2. Rate Limiting Check (Sliding Window per IP)
def check_rate_limit(client_ip: str) -> bool:
    now = time.time()
    record = RATE_LIMIT_STORE.get(client_ip, {"count": 0, "reset_at": now + 60})
    
    if now > record["reset_at"]:
        record = {"count": 1, "reset_at": now + 60}
    else:
        record["count"] += 1
        
    RATE_LIMIT_STORE[client_ip] = record
    return record["count"] > MAX_REQUESTS_PER_MINUTE

# 3. Async Token Generator
async def generate(prompt: str) -> AsyncGenerator[str, None]:
    text = f"Here is the detailed AI analysis for '{prompt}'. This was generated by the backend engine."
    for word in text.split(" "):
        yield word + " "
        await asyncio.sleep(0.08)

# 4. Main Streaming Endpoint
@app.post("/api/v1/chat")
async def chat_endpoint(request: Request, body: ChatRequest):
    client_ip = request.client.host if request.client else "127.0.0.1"
    
    # 🛡️ Step 1: Check Rate Limit (Returns HTTP 429 if exceeded)
    if check_rate_limit(client_ip):
        raise HTTPException(
            status_code=429,
            detail=f"Rate limit exceeded! Max {MAX_REQUESTS_PER_MINUTE} requests/minute allowed."
        )

    # ⚡ Step 2: Check Cache (Instant HIT)
    cache_key = get_cache_key(body.prompt)
    if cache_key in CACHE_STORE:
        cached_answer = CACHE_STORE[cache_key]
        print(f"🎯 Cache HIT for prompt: '{body.prompt}' (Served in < 5ms!)")
        
        async def cache_generator():
            yield f"data: {json.dumps({'token': cached_answer, 'cached': True})}\n\n"
            yield "data: [DONE]\n\n"
            
        return StreamingResponse(cache_generator(), media_type="text/event-stream")

    # 🔄 Step 3: Cache MISS -> Stream live & save to cache
    print(f"❌ Cache MISS for prompt: '{body.prompt}'. Streaming live...")

    async def event_generator():
        accumulated_tokens = []
        try:
            async for token in generate(body.prompt):
                if await request.is_disconnected():
                    print("⚠️ Client disconnected!")
                    return
                accumulated_tokens.append(token)
                yield f"data: {json.dumps({'token': token, 'cached': False})}\n\n"

            # Save full response to cache for all future users
            full_response = "".join(accumulated_tokens)
            CACHE_STORE[cache_key] = full_response
            print(f"💾 Saved to cache with key {cache_key[:8]}...")

            yield "data: [DONE]\n\n"
        except Exception as e:
            yield f"data: {json.dumps({'error': str(e)})}\n\n"

    return StreamingResponse(event_generator(), media_type="text/event-stream")

if __name__ == "__main__":
    uvicorn.run("06_caching_and_rate_limit:app", host="127.0.0.1", port=8000, reload=True)